[tool.poetry]
name = "netbox-lists"
version = "3.1.1"
description = ""
authors = ["Devon Mar <devonm@mdmm.ca>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.2"
netaddr = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
flake8 = "^5.0"
pynetbox = "^7.0.1"
requests = "^2.27.1"
isort = "^5.10.1"
black = "^22.8.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
force_alphabetical_sort_within_sections = true

[mypy]
plugins = ["mypy_django_plugin.main"]

disallow_any_generics = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "rest_framework.*",
    "taggit.*",
    "django_filters",
    "netaddr.*",
    # NetBox
    "dcim.*",
    "ipam.*",
    "extras.*",
    "virtualization.*",
]
ignore_missing_imports = true
